DIRS=sixaxis-emu sixaxis-emu-configurator sixemugui sixstatus

all:
	for i in $(DIRS); do cd $$i; make -f Makefile.win all; cd ..; done

clean:
	for i in $(DIRS); do cd $$i; make -f Makefile.win clean; cd ..; done
